### ISSUE TITLE
Local development WordPress breaks after enabling chicago-reporter theme

### ISSUE THREAD

**Issue by ghing** [INN/umbrella-chicagoreporter#3]
Hello, I've been doing a little bit of work with the Chicago Reporter and have run into an issue while trying to set up a local development environment. 

To set up my environment, I followed the instructions in INN's [Vagrant Setup Instructions](https://github.com/INN/docs/blob/master/staffing/onboarding/vvv-setup.md) and then the `vv create` values described in the [README](https://github.com/INN/umbrella-chicagoreporter/blob/master/README.md) for this project.

I'm able to access WordPress at `chicagoreporter.vagrant.dev` and login to the WordPress admin.

However, when I enable the `chicago-reporter` theme, I get a white screen in the admin and on the homepage.

Before enabling the `chicago-reporter` theme, this is my list of themes:

```
vagrant@vvv:/srv/www/chicagoreporter/htdocs$ wp theme list
+------------------+----------+--------+---------+
| name             | status   | update | version |
+------------------+----------+--------+---------+
| chicago-reporter | inactive | none   | 0.4     |
| largo            | active   | none   | 0.5.5.3 |
| twentyfifteen    | inactive | none   | 1.8     |
| twentyseventeen  | inactive | none   | 1.3     |
| twentysixteen    | inactive | none   | 1.3     |
+------------------+----------+--------+---------+
```

After enabling the theme, when I try to run `wp theme list`, I get these errors:

```
vagrant@vvv:/srv/www/chicagoreporter/htdocs$ wp theme list
Fatal error: Uncaught Error: Call to undefined function largo_add_meta_box() in /srv/www/chicagoreporter/htdocs/wp-content/themes/chicago-reporter/inc/metaboxes.php:5
Stack trace:
#0 /srv/www/chicagoreporter/htdocs/wp-content/themes/chicago-reporter/functions.php(40): require_once()
#1 /srv/www/chicagoreporter/htdocs/wp-includes/class-wp-hook.php(298): largo_child_require_files('')
#2 /srv/www/chicagoreporter/htdocs/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#3 /srv/www/chicagoreporter/htdocs/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /srv/www/chicagoreporter/htdocs/wp-settings.php(432): do_action('after_setup_the...')
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1046): require('/srv/www/chicag...')
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(983): WP_CLI\Runner->load_wordpress()
#7 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP in /srv/www/chicagoreporter/htdocs/wp-content/themes/chicago-reporter/inc/metaboxes.php on line 5
```

Does anyone have an idea of what's up?  Is the version of Largo too new for the Chicago Reporter theme, perhaps?

Also, where in the filesystem of the Vagrant box would I find the PHP error logs when I get a white screen of death?

**Comment by ghing** [comment]
I noticed that this repo contained submodules.  Instead of running:

    git clone git@github.com:INN/umbrella-chicagoreporter.git

as specified in the README,

I ran:

    git clone --recursive git@github.com:INN/umbrella-chicagoreporter.gi

and then re-copied the contents of `umbrella-chicagoreporter` into `htdocs`. 

Should I update the README, or should it have worked without the `--recursive`?

**Comment by rclachance** [comment]
hey @ghing, you're right `--recursive` should have been specified. I just updated the readme to reflect that.

On the whole, the setup process we have documented is overly complicated tedious, so our apologies for that. If you run into any other issues just give us a shout and we'd be happy to take a look.

**Comment by rclachance** [comment]
@benlk do you know where the error logs are on VVV? I've switched to Valet so I'm not using Vagrant any more on my dev machine.

**Comment by benlk** [comment]
In the vvv setup, they should be in /log/, probably in php_errors.log:

```
config/
database/
docs/
log/        <----
provision/
www/
CHANGELOG.md
CONTRIBUTING.md
LICENSE
README.md
Vagrantfile
Vagrantfile-backup
vv-blueprints.json
wp-cli.yml
```

```
/log$ ls
README.md          php_errors.log     xdebug-remote.log
                    ^
```

**Comment by benlk** [comment]
Also, yeah, this repo was never updated with the main boilerplate readme: https://github.com/INN/umbrella-boilerplate/blob/master/readme-template.md
